### ISSUE TITLE
malformed remote path

### ISSUE THREAD

**Issue by MisterEffiks** [breunigs/duplicity-acdcli#3]
Hi,
thanks for this great backend! I've looked for it some time ago with no result...

But i've a problem using it with duply and duplicity.
I've entered this path in the duply config:
TARGET='acd:///backups/server'
But the generated command for duplicity is:
/usr/local/bin/duplicity collection-status --name XXX --encrypt-key XXX --sign-key XXX --verbosity 8 --volsize 50 --log-file /var/log/ftpbackup.log --num-retries 5 --timeout=120 acd:/@//backups/server
With this malformed path acd_cli doesn't found the backup folder, of course.

Best regards,
MrFX

**Comment by breunigs** [comment]
Can you try lowering the count of slashes, I.e. To acd://backups or acd:/backups and see if that works?

**Comment by MisterEffiks** [comment]
no success,
with 2 slashes: acd://@backups/server
with just 1 this error: Bad URL '@acd:/backups/server'

**Comment by breunigs** [comment]
All this seems to happen before duplicity is called (and thus before this backend can run), it seems duply tries to include some authentication information into the URL. Since username and password don't really make sense in case of ACD, they end up empty and just the stray @ gets included. Looks like line 53 in Amazonclouddrivebackend.py was meant to handle this case.

Can you provide a complete example/script for duply that leads to this error, so I can reproduce locally?

**Comment by MisterEffiks** [comment]
shame on me ;)
With the latest duply version it works...
I had 2 copies of duply on my system, so it uses the older one.
